Editing feature for Courses
Steve-D-Eckles/tsct-portal pull request #12
Opened 2020-04-21 18:55 UTC by thienqui-communistspy

I added an editing feature for the courses.

2020-04-21 19:13 UTC, kevinlueke requested changes

2020-04-21 19:13 UTC, kevinlueke commented on portal/teacher.py
> +            print(courses)
This is for testing. Should be removed.

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/CourseCreation.html
> ++<form method='post'>
Closing form tag is indented but this one is not. Indent this one.

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/CourseCreation.html
> ++    </label>
Another indentation issue. Once these are fixed, might need to double check the rest of the indentation

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/CourseCreation.html
> ++        </select>
Indentation.

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/course-creation.html
> +{% block title %}Course creation '{}'{% endblock %}
What is this doing with the curly braces?

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/edit.html
> +        </label>
Indentation Issue.

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/edit.html
> +        <input type = "text" name = "course-description" id='description'/>
Indentation Issue

2020-04-21 19:13 UTC, kevinlueke commented on portal/templates/edit.html
> +        <input type = "submit" />
The indentation in this file is getting indented in areas it shouldn't be and it becomes clear on this line.

2020-04-21 19:13 UTC, kevinlueke commented on tests/test_teacher.py
> +from urllib.parse import urlparse
Isn't used so not needed.

2020-04-21 19:13 UTC, kevinlueke commented on tests/test_teacher.py
> +    #assert client.get('/teacher/courses/edit').status_code == 200
If these aren't being used they can be deleted.

2020-04-21 19:13 UTC, kevinlueke commented on tests/test_teacher.py
> +    #assert client.get('/teacher/courses/edit').status_code == 200
These meaning the commented out code.

2020-04-21 19:13 UTC, kevinlueke commented on tests/test_teacher.py
> +                (1, )
Get rid of that extra space.

2020-04-21 19:17 UTC, Steve-D-Eckles requested changes

2020-04-21 19:17 UTC, Steve-D-Eckles commented on portal/teacher.py
> +            print(courses)
make sure to get rid of debug code like this

2020-04-21 19:17 UTC, Steve-D-Eckles commented on tests/test_teacher.py
> +                assert res.headers['Location'] == 'http://localhost/teacher/courses'
include an empty line between the end of one function and the definition of the next for better readability

2020-04-21 19:17 UTC, Steve-D-Eckles commented on portal/templates/CourseCreation.html
> ++{% extends "layouts/base.html" %}
this file was renamed 'course-creation.html' and does not need to be added back in with the old name

2020-04-21 19:46 UTC, kevinlueke approved these changes

2020-04-22 16:42 UTC, Steve-D-Eckles approved these changes

2020-04-22 16:42 UTC, merged